management:
  endpoint:
    health:
      show-details: always
  health:
    jms:
      enabled: false
    diskSpace:
      enabled: false
artemis:
  broker-url: (tcp://localhost:61616,tcp://localhost:62616)?ha=true
  broker-user: amq
  broker-password: password
  broker-consumer-concurrency: 1
  destination: SpringAmqQueue
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    it.mauiroma: debug
    org.springframework: info
    org.apache.activemq.artemis: info